- hosts: all
  become: yes
  tasks:
       - name: Ensure that Apache is installed
         apt: name=apache2 update_cache=yes state=latest
       - name: Ensure that the service is running 
         service: name=apache2 state=started enabled=yes
         