
REPO := jorgeacf/scala

include ../../Makefile.main

.PHONY: help
help:

	@echo ""
	@echo "This is the make help for Apache Hadoop (${VERSION}) docker image"
	@echo ""
	@echo "  Run 'make build' to build the Hadoop docker image."
	@echo "  Run 'make run-multi slaves=n' to start Hadoop with n slaves."
	@echo "  Run 'make clean' to clean all Hadoop containers."
	@echo ""

